name: test-library

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

jobs:

  run:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '7.4']

    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Composer cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Composer install
      run: |
        composer install --prefer-dist --no-progress --no-suggest --ansi

    - name: Static checks
      run: |
        ./vendor/bin/grumphp --ansi

    - name: Regenerate composer.json
      run: |
        ./vendor/bin/robo gs:generate --ansi
